baseURL = 'https://EliteScapeNC.com/'
languageCode = 'en-us'
title = 'EliteScape - Homepage'
canonifyURLs = true

#theme = "aether"
#theme = "bilberry-hugo-theme"
#theme = "bootstrap-bp-hugo-startpage"
#theme = "hugo-theme-jane"
#theme = "hugo-theme-zen"
theme = "hugo-scroll"

# This is a "one page"-website, so we do not need these kinds of pages.
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© EliteScapeNC"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Elite Scape services in North Carolina"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    images = ["images/elite-scape-hero.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "EliteScape - North Carolina"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = true

    [params.meta]
        keywords = "elitescape, elitescapenc, landscape, holly springs, apex, cary, raleigh, north carolina, lawn, lawn care"