baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
canonifyURLs = true

#theme = "aether"
#theme = "bilberry-hugo-theme"
theme = "bootstrap-bp-hugo-startpage"
#theme = "hugo-theme-jane"
#theme = "hugo-theme-zen"
